export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";
export const SET_TOKEN = "SET_TOKEN";
export const SET_ROLE = "SET_ROLE";
export const SET_COURSE = "SET_COURSE";
export const SET_ID = "SET_ID";

//GET COURSES
export const FETCH_ENROLLED_COURSES_REQUEST = "FETCH_ENROLLED_COURSES_REQUEST";
export const FETCH_ENROLLED_COURSES_SUCCESS = "FETCH_ENROLLED_COURSES_SUCCESS";
export const FETCH_ENROLLED_COURSES_FAILURE = "FETCH_ENROLLED_COURSES_FAILURE";

//GET INSTRUCTORS
export const FETCH_INSTRUCTORS_REQUEST = "FETCH_INSTRUCTORS_REQUEST";
export const FETCH_INSTRUCTORS_SUCCESS = "FETCH_INSTRUCTORS_SUCCESS";
export const FETCH_INSTRUCTORS_FAILURE = "FETCH_INSTRUCTORS_FAILURE";
