export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";
export const SET_TOKEN = "SET_TOKEN";
export const SET_ROLE = "SET_ROLE";
export const SET_COURSE = "SET_COURSE";
export const SET_ID = "SET_ID";

//GET COURSES
export const FETCH_ENROLLED_COURSES_REQUEST = "FETCH_ENROLLED_COURSES_REQUEST";
export const FETCH_ENROLLED_COURSES_SUCCESS = "FETCH_ENROLLED_COURSES_SUCCESS";
export const FETCH_ENROLLED_COURSES_FAILURE = "FETCH_ENROLLED_COURSES_FAILURE";
export const FETCH_ALL_COURSES_REQUEST = "FETCH_ALL_COURSES_REQUEST";
export const FETCH_ALL_COURSES_SUCCESS = "FETCH_ALL_COURSES_SUCCESS";
export const FETCH_ALL_COURSES_FAILURE = "FETCH_ALL_COURSES_FAILURE";
export const SET_RECENT_COURSES = "SET_RECENT_COURSES";
export const SET_NEWEST_COURSES = "SET_NEWEST_COURSES";
//GET INSTRUCTORS
export const FETCH_INSTRUCTORS_REQUEST = "FETCH_INSTRUCTORS_REQUEST";
export const FETCH_INSTRUCTORS_SUCCESS = "FETCH_INSTRUCTORS_SUCCESS";
export const FETCH_INSTRUCTORS_FAILURE = "FETCH_INSTRUCTORS_FAILURE";
export const GET_INSTRUCTOR_BY_ID_REQUEST = "GET_INSTRUCTOR_BY_ID_REQUEST";
export const GET_INSTRUCTOR_BY_ID_SUCCESS = "GET_INSTRUCTOR_BY_ID_SUCCESS";
export const GET_INSTRUCTOR_BY_ID_FAILURE = "GET_INSTRUCTOR_BY_ID_FAILURE";

//SEARCH INSTRUCTORS
export const SEARCH_INSTRUCTORS_REQUEST = "SEARCH_INSTRUCTORS_REQUEST";
export const SEARCH_INSTRUCTORS_SUCCESS = "SEARCH_INSTRUCTORS_SUCCESS";
export const SEARCH_INSTRUCTORS_FAILURE = "SEARCH_INSTRUCTORS_FAILURE";

//SEARCH COURSES
export const SEARCH_COURSES_REQUEST = "SEARCH_COURSES_REQUEST";
export const SEARCH_COURSES_SUCCESS = "SEARCH_COURSES_SUCCESS";
export const SEARCH_COURSES_FAILURE = "SEARCH_COURSES_FAILURE";

//GET CERTIFICATES
export const FETCH_CERTIFICATES_REQUEST = "FETCH_CERTIFICATES_REQUEST";
export const FETCH_CERTIFICATES_SUCCESS = "FETCH_CERTIFICATES_SUCCESS";
export const FETCH_CERTIFICATES_FAILURE = "FETCH_CERTIFICATES_FAILURE";

//DELETE CERTIFICATES
export const DELETE_CERTIFICATES_REQUEST = "DELETE_CERTIFICATES_REQUEST";
export const DELETE_CERTIFICATES_SUCCESS = "DELETE_CERTIFICATES_SUCCESS";
export const DELETE_CERTIFICATES_FAILURE = "FETCH_CERTIFICATES_FAILURE";

//GET NEWS
//GET CERTIFICATES
export const FETCH_NEWS_REQUEST = "FETCH_NEWS_REQUEST";
export const FETCH_NEWS_SUCCESS = "FETCH_NEWS_SUCCESS";
export const FETCH_NEWS_FAILURE = "FETCH_NEWS_FAILURE";

//GET REVIEWS
export const FETCH_REVIEWS_REQUEST = "FETCH_REVIEWS_REQUEST";
export const FETCH_REVIEWS_SUCCESS = "FETCH_REVIEWS_SUCCESS";
export const FETCH_REVIEWS_FAILURE = "FETCH_REVIEWS_FAILURE";

//GET OURBLOG
export const FETCH_OURBLOG_REQUEST = "FETCH_OURBLOG_REQUEST";
export const FETCH_OURBLOG_SUCCESS = "FETCH_OURBLOG_SUCCESS";
export const FETCH_OURBLOG_FAILURE = "FETCH_OURBLOG_FAILURE";

//GET STATEMENTS
export const FETCH_STATEMENTS_REQUEST = 'FETCH_STATEMENTS_REQUEST';
export const FETCH_STATEMENTS_SUCCESS = 'FETCH_STATEMENTS_SUCCESS';
export const FETCH_STATEMENTS_FAILURE = 'FETCH_STATEMENTS_FAILURE';

//SEARCH REVIEW
export const SEARCH_REVIEWS_REQUEST = "SEARCH_REVIEW_REQUEST";
export const SEARCH_REVIEWS_SUCCESS = "SEARCH_REVIEW_SUCCESS";
export const SEARCH_REVIEWS_FAILURE = "SEARCH_REVIEW_FAILURE";
